site_name: "Lives in Transit: writers' guide"

theme:
    name: readthedocs

nav:
    - Home: index.md
    - Getting started: start.md
    - Validating content: validation.md
    - Screen layout: layout.md
    - About the project: about.md
